version: "3"

services:
  app:
    build: .
    container_name: todo-app
    ports:
      - "3001:3000"
    restart: always

  # Service optionnel : Base de donn√©es MongoDB
  mongodb:
    image: mongo
    container_name: todo-mongo
    ports:
      - "27017:27017"
